config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'address#index'

  resources :address, only: [:new, :index, :create]
end

app/models/Localisation.rb
class Localisation < ActiveRecord::Base

  validates :number, :street, :city, :postal_code, :country, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  protect_from_forgery with: :exception

  def index
    localisations = Localisation.all
    if params[:order] == 'ASC'
      localisations.order!('postal_code ASC')
    elsif params[:order] == 'DESC'
      localisations.order!('postal_code DESC')
    end
    render :index, locals:{localisations: localisations}
  end

  def create
    localisation = Localisation.new(address_params)
    unless localisation.valid?
      flash[:danger] = "Non valide !"
    else
      localisation.save
      flash[:info] = "Enregistré avec succès !"
    end
    redirect_to root_path
  end

  def new

  end

  protected
  def address_params
    params.permit(
        :number,
        :street,
        :city,
        :postal_code,
        :country
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
      when "info" then "alert alert-info"
      when "success" then "alert alert-success"
      when "warning" then "alert alert-warning"
      when "danger" then "alert alert-danger"
      else "alert alert-danger"
    end
  end

end

app/views/address/_form.html.slim
= form_tag(controller: "address", action: "create", method: "post") do
  .field
    = label_tag :address, "Adresse :"
    = text_field_tag :address

    div style = "display:none"
      = text_field_tag :number
      = text_field_tag :street
      = text_field_tag :city
      = text_field_tag :postal_code
      = text_field_tag :country


    = submit_tag 'Save '

app/views/address/index.html.slim
h1 Adress Picker
div
  .btn-group role="group"
    =link_to 'croissant', address_index_path(order: 'ASC'), class:"btn btn-default"
    =link_to 'decroissant', address_index_path(order: 'DESC'), class:"btn btn-default"

  =link_to 'ajouter une adresse', new_address_path, class:"btn btn-primary"
div
  table.table.table-striped
    thead
      th numéro
      th rue
      th ville
      th code postal
      th pays
    tbody
      -localisations.each do |localisation|
        tr
          td =localisation.number
          td =localisation.street
          td =localisation.city
          td =localisation.postal_code
          td =localisation.country

app/views/address/new.html.slim
= render partial: 'form'

app/views/layouts/_head.html.slim
head
  meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  title Address picker

  == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
  script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&key=AIzaSyB0CuenxncN6WymAy4GOwUizeYsBmd2oZk"
  == javascript_include_tag 'application', 'data-turbolinks-track' => true

  == csrf_meta_tags

app/views/layouts/application.html.slim
doctype html
html
  == render "layouts/head"
  body class="#{yield(:body_class)}"
    .container
      - flash.each do |type, message|
        div id="message" class = flash_class(type)
          = message
      == yield